server:
  port: 8090

spring:
  application:
    name: backend-for-frontend-service

logging:
  level:
    com.sentinel.backend_for_frontend_service: DEBUG
    
services:
  tenant:
    url: http://localhost:8082
  project:
    url: http://localhost:8084
